Repository formium/tsdx, pull requests merged in 2020-09, with the labels that each got.

#855 docs: add `patch-package` reference to Customization section
  README.md
Labels: docs

#752 docs: capitalize 'S' in TypeScript
  CONTRIBUTING.md
  README.md
  src/deprecated.ts
  website/pages/index.mdx
Labels: problem/stale, scope/docs

#644 (fix): change plugin order to make styled-components/macro work
  src/babelPluginTsdx.ts
  test/integration/fixtures/build-withBabel/.babelrc.js
  test/integration/fixtures/build-withBabel/src/styled.tsx
  test/integration/tsdx-build-withBabel.test.ts
Labels: scope/integration, version/minor

#862 multi-entry: temporarily change docs to singular "module"
  README.md
  src/index.ts
Labels: scope/docs, topic/multi-entry

#870 fix: remove redundant CI env from workflow steps
  templates/basic/.github/workflows/main.yml
  templates/react-with-storybook/.github/workflows/main.yml
  templates/react/.github/workflows/main.yml
Labels: scope/templates

#789 Upgrade from rollup-plugin-babel to @rollup/plugin-babel
  package.json
  src/babelPluginTsdx.ts
  src/createRollupConfig.ts
  src/env.d.ts
  yarn.lock
Labels: problem/stale, scope/dependencies, topic/Node 10+, version/minor

#879 deps: upgrade several more deps' majors
  package.json
  src/createRollupConfig.ts
  yarn.lock
Labels: scope/dependencies, topic/Node 10+

#881 docs: remove reference to Node 10+ req for create
  README.md
Labels: scope/docs, topic/Node 10+

#880 ci: update matrix to use Node 14 instead of Node 13
  .github/workflows/nodejs.yml
Labels: scope/internal

#876 feat: type-check stories during Storybook build
  templates/react-with-storybook/.storybook/main.js
Labels: scope/templates
