Repository formium/tsdx, pull requests merged in 2020-08, with the labels that each got.

#805 update react-with-storybook template for Storybook v6
  src/templates/react-with-storybook.ts
  templates/react-with-storybook/.storybook/main.js
  templates/react-with-storybook/.storybook/preview.js
  templates/react-with-storybook/README.md
  templates/react-with-storybook/src/index.tsx
  templates/react-with-storybook/stories/Thing.stories.tsx
Labels: template

#683 deps: add deduplicate script and apply yarn-deduplicate
  .github/workflows/nodejs.yml
  package.json
  yarn.lock
Labels: dependencies, optimization

#838 deps: upgrade Babel preset-env, remove now redundant plugins
  package.json
  src/babelPluginTsdx.ts
  test/integration/tsdx-build-withConfig.test.ts
  yarn.lock
Labels: dependencies

#705 Add size-limit bundle size analysis tool
  src/createRollupConfig.ts
  src/env.d.ts
  src/templates/basic.ts
  src/templates/utils/index.ts
  templates/basic/.github/workflows/size.yml
  templates/basic/README.md
  templates/react-with-storybook/.github/workflows/size.yml
  templates/react-with-storybook/README.md
  templates/react/.github/workflows/size.yml
  templates/react/README.md
Labels: template

#846 env/deps: remove greenkeeper.json, configure dependabot.yml
  .github/dependabot.yml
  greenkeeper.json
Labels: dependencies

#850 fix/deps: dependabot YAML doesn't support anchors/aliases
  .github/dependabot.yml
Labels: dependencies
